-- Script was generated by Devart dbForge Studio for MySQL, Version 4.50.285.0
-- Script date 14/11/2013 17:14:37
-- Server version: 5.6.12-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for database sysclinico
--
DROP DATABASE IF EXISTS sysclinico;
CREATE DATABASE IF NOT EXISTS sysclinico
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Set default database
--
USE sysclinico;

--
-- Definition for table tb_departamento
--
CREATE TABLE IF NOT EXISTS tb_departamento (
  departamentoid INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(30) NOT NULL,
  PRIMARY KEY (departamentoid)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_estadocivil
--
CREATE TABLE IF NOT EXISTS tb_estadocivil (
  estadocivilid INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(12) DEFAULT NULL,
  PRIMARY KEY (estadocivilid)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_paciente
--
CREATE TABLE IF NOT EXISTS tb_paciente (
  pacienteid INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(30) NOT NULL,
  apepaterno VARCHAR(30) NOT NULL,
  apematerno VARCHAR(30) NOT NULL,
  estadcivil CHAR(1) NOT NULL,
  edad DECIMAL(2, 0) NOT NULL,
  ocupacion VARCHAR(50) DEFAULT NULL,
  lugarnac VARCHAR(50) DEFAULT NULL,
  lugarproc VARCHAR(30) DEFAULT NULL,
  domicilio CHAR(150) DEFAULT NULL,
  telefono DECIMAL(10, 0) DEFAULT NULL,
  PRIMARY KEY (pacienteid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_historiaclinica
--
CREATE TABLE IF NOT EXISTS tb_historiaclinica (
  historiaclinicaid INT(11) NOT NULL AUTO_INCREMENT,
  medicos VARCHAR(150) DEFAULT NULL,
  quirurgicos VARCHAR(200) DEFAULT NULL,
  alergicos VARCHAR(200) DEFAULT NULL,
  fur VARCHAR(100) DEFAULT NULL,
  menarquia VARCHAR(100) DEFAULT NULL,
  rs VARCHAR(100) DEFAULT NULL,
  rc VARCHAR(100) DEFAULT NULL,
  g DECIMAL(3, 0) DEFAULT NULL,
  p DECIMAL(3, 0) DEFAULT NULL,
  ma VARCHAR(100) DEFAULT NULL,
  hospitalizacion VARCHAR(200) DEFAULT NULL,
  habitosnocivos VARCHAR(200) DEFAULT NULL,
  pacienteid INT(11) DEFAULT NULL,
  PRIMARY KEY (historiaclinicaid),
  UNIQUE INDEX pacienteid (pacienteid),
  CONSTRAINT FK_tb_historiaclinica_tb_paciente_pacienteid FOREIGN KEY (pacienteid)
    REFERENCES tb_paciente(pacienteid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_provincia
--
CREATE TABLE IF NOT EXISTS tb_provincia (
  provinciaid INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(30) NOT NULL,
  departamentoid INT(11) NOT NULL,
  PRIMARY KEY (provinciaid),
  INDEX FK_tb_provincia_tb_departamento_departamentoid (departamentoid),
  CONSTRAINT FK_tb_provincia_tb_departamento_departamentoid FOREIGN KEY (departamentoid)
    REFERENCES tb_departamento(departamentoid)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_distrito
--
CREATE TABLE IF NOT EXISTS tb_distrito (
  distritoid INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(30) NOT NULL,
  provinciaid INT(11) NOT NULL,
  PRIMARY KEY (distritoid),
  INDEX FK_tb_distrito_tb_provincia_provinciaid (provinciaid),
  CONSTRAINT FK_tb_distrito_tb_provincia_provinciaid FOREIGN KEY (provinciaid)
    REFERENCES tb_provincia(provinciaid)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_informe
--
CREATE TABLE IF NOT EXISTS tb_informe (
  informeid INT(11) NOT NULL AUTO_INCREMENT,
  descripcion TEXT NOT NULL,
  conclusion TEXT NOT NULL,
  historiaclinicaid INT(11) NOT NULL,
  PRIMARY KEY (informeid),
  INDEX FK_tb_informe_tb_historiaclinica_historiaclinicaid (historiaclinicaid),
  CONSTRAINT FK_tb_informe_tb_historiaclinica_historiaclinicaid FOREIGN KEY (historiaclinicaid)
    REFERENCES tb_historiaclinica(historiaclinicaid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_persona
--
CREATE TABLE IF NOT EXISTS tb_persona (
  personaid INT(11) NOT NULL AUTO_INCREMENT,
  nombres VARCHAR(50) DEFAULT NULL,
  apepaterno VARCHAR(30) NOT NULL,
  apematerno VARCHAR(30) NOT NULL,
  nombcompleto VARCHAR(50) DEFAULT NULL,
  fechnacimiento DATE NOT NULL,
  domicilio VARCHAR(100) DEFAULT NULL,
  telefono DECIMAL(10, 0) DEFAULT NULL,
  dni VARCHAR(8) NOT NULL,
  distritoid INT(11) NOT NULL,
  estadocivilid INT(11) NOT NULL,
  PRIMARY KEY (personaid),
  INDEX FK_tb_persona_tb_distrito_distritoid (distritoid),
  INDEX FK_tb_persona_tb_estadocivil_estadocivilid (estadocivilid),
  CONSTRAINT FK_tb_persona_tb_distrito_distritoid FOREIGN KEY (distritoid)
    REFERENCES tb_distrito(distritoid),
  CONSTRAINT FK_tb_persona_tb_estadocivil_estadocivilid FOREIGN KEY (estadocivilid)
    REFERENCES tb_estadocivil(estadocivilid)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_medico
--
CREATE TABLE IF NOT EXISTS tb_medico (
  medicoid INT(11) NOT NULL AUTO_INCREMENT,
  personaid INT(11) NOT NULL,
  PRIMARY KEY (medicoid),
  UNIQUE INDEX personaid (personaid),
  CONSTRAINT FK_tb_medico_tb_persona_personaid FOREIGN KEY (personaid)
    REFERENCES tb_persona(personaid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_secretaria
--
CREATE TABLE IF NOT EXISTS tb_secretaria (
  secretariaid INT(11) NOT NULL AUTO_INCREMENT,
  personaid INT(11) NOT NULL,
  PRIMARY KEY (secretariaid),
  UNIQUE INDEX personaid (personaid),
  CONSTRAINT FK_tb_secretaria_tb_persona_personaid FOREIGN KEY (personaid)
    REFERENCES tb_persona(personaid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_usuario
--
CREATE TABLE IF NOT EXISTS tb_usuario (
  usuarioid INT(11) NOT NULL AUTO_INCREMENT,
  usuario VARCHAR(100) NOT NULL,
  contrasenia VARCHAR(100) DEFAULT NULL,
  tiposuario VARCHAR(20) NOT NULL,
  personaid INT(11) NOT NULL,
  PRIMARY KEY (usuarioid),
  UNIQUE INDEX personaid (personaid),
  CONSTRAINT FK_tb_usuario_tb_persona_personaid FOREIGN KEY (personaid)
    REFERENCES tb_persona(personaid)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_cita
--
CREATE TABLE IF NOT EXISTS tb_cita (
  citaid INT(11) NOT NULL AUTO_INCREMENT,
  especialidad VARCHAR(50) NOT NULL,
  tipocita CHAR(1) NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  secretariaid INT(11) NOT NULL,
  pacienteid INT(11) NOT NULL,
  PRIMARY KEY (citaid),
  INDEX FK_tb_cita_tb_paciente_pacienteid (pacienteid),
  INDEX FK_tb_cita_tb_secretaria_secretariaid (secretariaid),
  CONSTRAINT FK_tb_cita_tb_paciente_pacienteid FOREIGN KEY (pacienteid)
    REFERENCES tb_paciente(pacienteid),
  CONSTRAINT FK_tb_cita_tb_secretaria_secretariaid FOREIGN KEY (secretariaid)
    REFERENCES tb_secretaria(secretariaid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_consulta
--
CREATE TABLE IF NOT EXISTS tb_consulta (
  consultaid INT(11) NOT NULL AUTO_INCREMENT,
  pacienteid INT(11) NOT NULL,
  medicoid INT(11) NOT NULL,
  fechaatencion DATE NOT NULL,
  motivo VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (consultaid),
  INDEX FK_tb_consulta_tb_medico_medicoid (medicoid),
  CONSTRAINT FK_tb_consulta_tb_medico_medicoid FOREIGN KEY (medicoid)
    REFERENCES tb_medico(medicoid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tb_diagnostico
--
CREATE TABLE IF NOT EXISTS tb_diagnostico (
  diagnosticoid INT(11) NOT NULL AUTO_INCREMENT,
  tiemenferm VARCHAR(30) NOT NULL,
  sp VARCHAR(30) DEFAULT NULL,
  relato TEXT DEFAULT NULL,
  fc VARCHAR(20) DEFAULT NULL,
  pa VARCHAR(20) DEFAULT NULL,
  fr VARCHAR(10) DEFAULT NULL,
  temperatura CHAR(2) DEFAULT NULL,
  peso DECIMAL(3, 0) DEFAULT NULL,
  cabeza VARCHAR(10) DEFAULT NULL,
  cuello VARCHAR(10) DEFAULT NULL,
  toraxpulmones VARCHAR(10) DEFAULT NULL,
  cardiovascular VARCHAR(5) DEFAULT NULL,
  abdomen TEXT DEFAULT NULL,
  genitourinario TEXT DEFAULT NULL,
  locomotor VARCHAR(10) DEFAULT NULL,
  neurologico VARCHAR(10) DEFAULT NULL,
  dx1 VARCHAR(50) DEFAULT NULL,
  dx2 VARCHAR(50) DEFAULT NULL,
  dx3 VARCHAR(50) DEFAULT NULL,
  dx4 VARCHAR(50) DEFAULT NULL,
  tratamiento1 VARCHAR(50) DEFAULT NULL,
  tratamiento2 VARCHAR(50) DEFAULT NULL,
  tratamiento3 VARCHAR(50) DEFAULT NULL,
  tratamiento4 VARCHAR(50) DEFAULT NULL,
  exauxiliares TEXT DEFAULT NULL,
  consultaid INT(11) DEFAULT NULL,
  historiaclinicaid INT(11) NOT NULL,
  PRIMARY KEY (diagnosticoid),
  UNIQUE INDEX consultaid (consultaid),
  INDEX FK_tb_diagnostico_tb_historiaclinica_historiaclinicaid (historiaclinicaid),
  CONSTRAINT FK_tb_diagnostico_tb_consulta_consultaid FOREIGN KEY (consultaid)
    REFERENCES tb_consulta(consultaid),
  CONSTRAINT FK_tb_diagnostico_tb_historiaclinica_historiaclinicaid FOREIGN KEY (historiaclinicaid)
    REFERENCES tb_historiaclinica(historiaclinicaid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table tb_departamento
--
INSERT INTO tb_departamento VALUES 
  (1, 'Lima');

-- 
-- Dumping data for table tb_estadocivil
--
INSERT INTO tb_estadocivil VALUES 
  (1, 'soltero'),
  (2, 'casado'),
  (3, 'viudo'),
  (4, 'divorciado');

-- 
-- Dumping data for table tb_paciente
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tb_historiaclinica
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tb_provincia
--
INSERT INTO tb_provincia VALUES 
  (1, 'huaral', 1);

-- 
-- Dumping data for table tb_distrito
--
INSERT INTO tb_distrito VALUES 
  (1, 'huaral', 1);

-- 
-- Dumping data for table tb_informe
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tb_persona
--
INSERT INTO tb_persona VALUES 
  (1, 'jorge luis', 'torres', 'colan', 'jorge luis torres', '1992-07-31', 'la huaquilla', 996514952, '47351151', 1, 1);

-- 
-- Dumping data for table tb_medico
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tb_secretaria
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tb_usuario
--
INSERT INTO tb_usuario VALUES 
  (1, 'jorge', '12345', 'administrador', 1);

-- 
-- Dumping data for table tb_cita
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tb_consulta
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tb_diagnostico
--
-- Table does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;